### PR TITLE
fix obsolete assumptions that Char == UTF-32

### LINKED ISSUE #38: Is it possible to construct a UTF32String from an Array{Char, 1}?
From the error prompt from my REPL I thought it would be possible to construct a UTF32String from Array{Char, 1}. However, when I try to do so, I get

```
julia> t = "asdf"
"asdf"

julia> c = Vector{Char}(t)
4-element Array{Char,1}:
 'a'
 's'
 'd'
 'f'

julia> UTF32String(c)

ERROR: MethodError: no method matching UTF32String(::Base.ReinterpretArray{UInt32,1,Char,Array{Char,1}})
Closest candidates are:
  UTF32String(::Array{UInt32,1}) at /home/jx/.julia/packages/LegacyStrings/tkVHE/src/LegacyStrings.jl:96
  UTF32String(::Array{Char,1}) at /home/jx/.julia/packages/LegacyStrings/tkVHE/src/utf32.jl:3
Stacktrace:
 [1] UTF32String(::Array{Char,1}) at /home/jx/.julia/packages/LegacyStrings/tkVHE/src/utf32.jl:3
 [2] top-level scope at none:0
```

which is weird to me since the second candidate literally says `UTF32String(::Array{Char,1})`.

Is the only way to construct a UTF32String via `utf32(s)`?

### PR DESCRIPTION
**Pull request by stevengj**
When this code was originally written (< Julia 0.6), `Char` was bit-equivalent to UTF-32, but in Julia 1.x that is no longer the case and a bunch of code was broken.   This PR fixes those issues.

(The code could be further optimized to allocate fewer temporary arrays during conversions, but I doubt it's worth it nowadays.)

Fixes #38.

### CODE REVIEW

File: src/utf32.jl [hunk 1]
```diff
@@ -137,10 +137,10 @@ end
 convert(::Type{UTF32String}, data::AbstractVector{Int32}) =
     convert(UTF32String, reinterpret(UInt32, convert(Vector{Int32}, data)))
 
-convert(::Type{UTF32String}, data::AbstractVector{Char}) =
+convert(::Type{UTF32String}, data::AbstractVector{<:AbstractChar}) =
     convert(UTF32String, map(UInt32, data))
 
-convert(::Type{T}, v::AbstractVector{S}) where {T<:AbstractString, S<:Union{UInt32,Char,Int32}} =
+convert(::Type{T}, v::AbstractVector{S}) where {T<:Union{ASCIIString,UTF16String}, S<:Union{UInt32,AbstractChar,Int32}} =
```
Comment (stevengj) [inline src/utf32.jl:143]: Note that the old method here was type piracy.  (There are probably some other instances of type piracy in this ancient package, but I don't have the inclination to conduct an audit.)
